## <h2 style="text-align:center;color:red;font-family:cursive">101 Pandas Practice Questions.</h2>
### <h3 style="text-align:left;color:skyblue;font-family:cursive">From basic to Intermediate.</h3>
#### (23-44) Questions.

In [1]:
import pandas as pd
import numpy as np
import random

## Question - 23
### Problem Statement : How to convert year-month string to dates corresponding to the 4th day of the month?

In [2]:
from dateutil.parser import parse
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser.map(lambda x:parse('04'+x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

## Question - 24
### Problem Statement : How to filter words that contain atleast 2 vowels from a series?

In [3]:
def no_of_vowels(item):
    vowels = ['a','e','i','o','u']
    lis = []
    
    for j in item:
        count = 0
        for i in j.lower():
            if i in vowels:
                count+=1
        if count >= 2:
            lis.append(j)
    return lis
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
res = no_of_vowels(ser)
res = pd.DataFrame(res)
res


0
0   Apple
1  Orange
2   Money

## Question - 25
### Problem Statement : How to filter valid emails from a series?

In [4]:
import re
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
#solution 1
def filter_emails(emails):
    lis = []
    for email in emails:
        if re.findall(pattern,email):
            lis.append(email)
    return pd.DataFrame(lis)
print(filter_emails(emails))

print()
print('########################################')
print()

#solution 2
mask = emails.map(lambda x:bool(re.match(pattern,x)))
print(emails[mask])

                   0
0  rameses@egypt.com
1          matt@t.co
2  narendra@modi.com

########################################

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


## Question - 26
### Problem Statement : How to get the mean of a series grouped by another series?

In [5]:
#Compute the mean of weights of each fruit.
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())
weights.groupby(fruit).mean()



[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'banana', 'banana', 'banana', 'banana', 'apple', 'banana', 'banana', 'carrot', 'carrot']


apple     6.000000
banana    4.285714
carrot    9.500000
dtype: float64

## Question - 27
### Problem Statement : How to compute the euclidean distance between two series?

In [6]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

#Solution 1
print(np.round(np.sqrt(np.sum(np.square(p-q))),3))

#Solution 2
print(np.linalg.norm(p-q))


18.166
18.16590212458495


## Question - 28
### Problem Statement : How to find all the local maxima (or peaks) in a numeric series?

In [7]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
diff = np.diff(np.sign(np.diff(ser)))
print(diff)
peak = np.where(diff == -2)[0]+1
peak



[-2  2  0  0 -2  2 -2]


array([1, 5, 7], dtype=int64)

## Question - 29
### Problem Statement : How to replace missing spaces in a string with the least frequent character?

In [8]:
my_str = 'dbc deb abed gade'
df = pd.Series(list(my_str))
freq = df.value_counts()
least_frequency = freq.dropna().index[-1]
''.join(str(my_str.replace(' ',least_frequency)))

'dbccdebcabedcgade'

## Question - 30
### Problem Statement : How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

In [9]:
a = np.random.randint(0,10,10)
b = pd.date_range('2000-01-01',periods=10)
res = pd.Series(a,b)
res

2000-01-01    4
2000-01-02    7
2000-01-03    9
2000-01-04    3
2000-01-05    7
2000-01-06    5
2000-01-07    7
2000-01-08    1
2000-01-09    9
2000-01-10    6
Freq: D, dtype: int32

## <h2 style="color:skyblue;font-family:cursive">Question : 31</h2>
### Problem Statement : How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?

In [10]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser.resample('D').ffill() 

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

## Question - 32
### Problem Statement : How to compute the autocorrelations of a numeric series?

In [11]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
# print(np.random.normal(1,10,20))
# np.arange(20)
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
autocorrelations

[1.0, 0.29, 0.2, 0.61, 0.46, 0.16, 0.47, 0.26, 0.08, 0.88, -0.05]

## Question - 33
### Problem Statement : How to import only every nth row from a csv file to create a dataframe?

In [12]:
# Solution 1
df = pd.read_csv('Advertising.csv',chunksize=50)
df2 = pd.DataFrame()

for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
df2

#Solution 2
import csv
df = pd.read_csv('Advertising.csv')
with open('Advertising.csv','r') as f:
    reader = csv.reader(f)
    res = []
    for i,row in enumerate(reader):
        if i%50 == 0:
            res.append(i)
# res [0, 50, 100, 150, 200]

for i in res:
    (df.iloc[i])

IndexError: single positional indexer is out-of-bounds

## Question - 34
### Problem Statement : How to change column values when importing csv to a dataframe?

In [ ]:
#Solution 1
df = pd.read_csv('BostonHousing.csv',converters={'medv':lambda x: 'High' if float(x) > 25 else 'Low'})
df.head()

#Solution 2
import csv
with open('BostonHousing.csv','r') as f:
    reader = csv.reader(f)
    out = []
    for i,row in enumerate(reader):
        if i>0:
            row[13] = 'High' if float(row[13]) > 25 else 'Low'
        out.append(row)
df = pd.DataFrame(out[1:], columns=out[0])
df.head()

crim  zn indus chas    nox     rm   age     dis rad  tax ptratio  \
0  0.00632  18  2.31    0  0.538  6.575  65.2    4.09   1  296    15.3   
1  0.02731   0  7.07    0  0.469  6.421  78.9  4.9671   2  242    17.8   
2  0.02729   0  7.07    0  0.469  7.185  61.1  4.9671   2  242    17.8   
3  0.03237   0  2.18    0  0.458  6.998  45.8  6.0622   3  222    18.7   
4  0.06905   0  2.18    0  0.458  7.147  54.2  6.0622   3  222    18.7   

        b lstat  medv  
0   396.9  4.98   Low  
1   396.9  9.14   Low  
2  392.83  4.03  High  
3  394.63  2.94  High  
4   396.9  5.33  High

## Question - 35
### Problem Statement : How to create a dataframe with rows as strides from a given series?

In [ ]:
L = pd.Series(range(15))
df = pd.DataFrame(L)
df.head()
##If anyone have better solution please contact:Github : 45_Hrishi

0
0  0
1  1
2  2
3  3
4  4

## Question - 36
### Problem Statement : How to import only specified columns from a csv file?

In [ ]:
df = pd.read_csv('BostonHousing.csv',usecols=('crim','medv'))
df.head()

crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2

## Question - 37
### Problem Statement : How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.

In [ ]:
df = pd.read_csv('BostonHousing.csv')
df.info()
print(df.shape)
print(df.dtypes)
print(df.dtypes.value_counts())
print(df.values.tolist()[:5])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB
(506, 14)
crim       float64
zn         float64
indus      float64
chas         int64
nox        float64
rm         float64
age        float64
dis        float64
rad          int64
tax          int64
ptratio    float64
b          float

## <h2 style="color:skyblue;font-family:cursive">Question - 38</h2>
### Problem Statement : How to extract the row and column number of a particular cell with given criterion?

In [ ]:
df = pd.read_csv('BostonHousing.csv')
maximum = max(df['age'])
df[df['age'] == maximum]
row,col = np.where(df.values == maximum)
row,col

(array([  8,  23,  31,  57, 141, 142, 143, 145, 146, 151, 158, 159, 209,
        258, 259, 367, 368, 371, 373, 374, 379, 382, 383, 386, 388, 398,
        400, 401, 402, 405, 406, 407, 409, 410, 411, 412, 413, 414, 415,
        418, 420, 437, 442, 443], dtype=int64),
 array([6, 6, 6, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       dtype=int64))

## Question - 39
### Problem Statement :  How to rename a specific columns in a dataframe?

In [33]:
df = pd.read_csv('BostonHousing.csv')
df.columns
df.rename(columns={'tax':'Tax'},inplace=True)
df.columns #tax to Tax

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'Tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

## Question - 40
### Problem Statement : How to check if a dataframe has any missing values?

In [36]:
df = pd.read_csv('BostonHousing.csv')
df.isnull().values.any()

False

## Question - 41
### Problem Statement :  How to count the number of missing values in each column?

In [39]:
df = pd.read_csv('BostonHousing.csv')
df.isnull().sum().argmax()

0

## Question - 42
### Problem Statement : How to replace missing values of multiple numeric columns with the mean?

In [54]:
df = pd.read_csv('Githubusers.csv')
res_df = df[['Min.Price','max.Price']] = df[['Min.Price','Max.Price']].apply(lambda x: x.fillna(x.mean()))

## <h2 style="font-family:cursive;color:skyblue">Question - 43</h2>
### Problem Statement : How to use apply function on existing columns with global variables as additional arguments?

In [57]:
df = pd.read_csv('Githubusers.csv')
d = {'Min.Price':np.nanmean,'Max.Price':np.nanmean}
res_df = df[['Min.Price','Max.Price']] = df[['Min.Price','Max.Price']].apply(lambda x,d:x.fillna(d[x.name](x)),args=(d,))
res_df

Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]

## Question - 44
### Problem Statement : How to select a specific column from a dataframe as a dataframe instead of a series?

In [61]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
new_df = df[['a']]
new_df

a
0   0
1   5
2  10
3  15